server {
    listen 80;
    listen [::]:80;
    server_name bmusic.ftwegc.com;
    server_tokens off;
    location ^~ /.well-known/acme-challenge/ { root /var/lib/bmusic/acme; }
    location / { return 503; }
}
