#!/usr/bin/env bash
# Run as root after uploading these files into /home/ubuntu/bmusic-upload.
set -euo pipefail
release="${1:?release tag required}"
[[ "$release" =~ ^[a-zA-Z0-9_.-]+$ ]] || exit 2
root=/opt/bmusic
stage=/home/ubuntu/bmusic-upload
if [[ -e "$root" && ! -f "$root/.managed-by-bmusic" ]]; then
    echo "Refusing to overwrite an unmanaged /opt/bmusic" >&2; exit 3
fi
if [[ -f "$root/.managed-by-bmusic" ]]; then
    grep -Fxq bmusic.ftwegc.com "$root/.managed-by-bmusic"
else
    if ss -H -lnt '( sport = :13100 or sport = :18100 )' | grep -q .; then
        echo "Reserved B-Music ports are occupied" >&2; exit 4
    fi
    [[ ! -e /etc/nginx/sites-available/bmusic.conf && ! -e /etc/nginx/sites-enabled/bmusic.conf ]]
    if nginx -T 2>/dev/null | grep -Fq 'server_name bmusic.ftwegc.com'; then
        echo "Domain already has an unmanaged Nginx configuration" >&2; exit 5
    fi
fi
install -d -m 0750 "$root" "$root/releases" "$root/private"
install -m 0644 "$stage/managed-marker" "$root/.managed-by-bmusic"
install -d -m 0755 /var/lib/bmusic/acme
install -m 0644 "$stage/compose.yml" "$root/compose.yml"
install -m 0600 "$stage/release.env" "$root/.env"
if [[ ! -e /etc/letsencrypt/live/bmusic.ftwegc.com/fullchain.pem ]]; then
    install -m 0644 "$stage/nginx-http.conf" /etc/nginx/sites-available/bmusic.conf
    if [[ ! -e /etc/nginx/sites-enabled/bmusic.conf ]]; then ln -s /etc/nginx/sites-available/bmusic.conf /etc/nginx/sites-enabled/bmusic.conf; fi
    nginx -t
    systemctl reload nginx
    certbot certonly --webroot -w /var/lib/bmusic/acme -d bmusic.ftwegc.com --cert-name bmusic.ftwegc.com --non-interactive --agree-tos --register-unsafely-without-email
fi
install -m 0755 "$stage/renew-nginx.sh" /etc/letsencrypt/renewal-hooks/deploy/bmusic-nginx-reload
install -d -m 0755 "$root/data" "$root/data/app" "$root/data/kernel" "$root/releases/$release"
if [[ -f "$stage/data.tar.gz" && ! -f "$root/.data-imported" ]]; then
    [[ ! -e "$root/data/app/bili-music-app.sqlite" && ! -e "$root/data/kernel/kernel.sqlite3" ]]
    # Archive is generated by prepare-data.mjs and contains only app/ and kernel/.
    tar -tzf "$stage/data.tar.gz" | awk '/(^\/|(^|\/)\.\.($|\/))/ {bad=1} END {exit bad}'
    tar -xzf "$stage/data.tar.gz" --no-same-owner -C "$root/data"
    install -m 0600 "$stage/managed-marker" "$root/.data-imported"
fi
[[ "$(realpath "$root/data/app")" = "$root/data/app" ]]
chown -R 10001:10001 "$root/data/app"
chmod 0750 "$root/data/app" "$root/data/kernel"
if [[ -f "$stage/source.tar.gz" ]]; then
    install -d -m 0755 "$root/releases/$release/source"
    tar -xzf "$stage/source.tar.gz" --no-same-owner -C "$root/releases/$release/source"
fi
docker compose --project-directory "$root" --env-file "$root/.env" -f "$root/compose.yml" up -d --wait --wait-timeout 180
install -m 0644 "$stage/nginx.conf" /etc/nginx/sites-available/bmusic.conf
if [[ ! -e /etc/nginx/sites-enabled/bmusic.conf ]]; then ln -s /etc/nginx/sites-available/bmusic.conf /etc/nginx/sites-enabled/bmusic.conf; fi
nginx -t
systemctl reload nginx
echo "B-Music deployed: https://bmusic.ftwegc.com"
